/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ApiRouteImport } from './routes/api'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginBonusIndexRouteImport } from './routes/login-bonus/index'
import { Route as ProfileSelectRouteImport } from './routes/profile/select'
import { Route as ProfileDoneRouteImport } from './routes/profile/done'
import { Route as ProfileCreateRouteImport } from './routes/profile/create'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginBonusIndexRoute = LoginBonusIndexRouteImport.update({
  id: '/login-bonus/',
  path: '/login-bonus/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSelectRoute = ProfileSelectRouteImport.update({
  id: '/profile/select',
  path: '/profile/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDoneRoute = ProfileDoneRouteImport.update({
  id: '/profile/done',
  path: '/profile/done',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreateRoute = ProfileCreateRouteImport.update({
  id: '/profile/create',
  path: '/profile/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/error': typeof ErrorRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/done': typeof ProfileDoneRoute
  '/profile/select': typeof ProfileSelectRoute
  '/login-bonus': typeof LoginBonusIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/error': typeof ErrorRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/done': typeof ProfileDoneRoute
  '/profile/select': typeof ProfileSelectRoute
  '/login-bonus': typeof LoginBonusIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/error': typeof ErrorRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/done': typeof ProfileDoneRoute
  '/profile/select': typeof ProfileSelectRoute
  '/login-bonus/': typeof LoginBonusIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api'
    | '/error'
    | '/profile/create'
    | '/profile/done'
    | '/profile/select'
    | '/login-bonus'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api'
    | '/error'
    | '/profile/create'
    | '/profile/done'
    | '/profile/select'
    | '/login-bonus'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/error'
    | '/profile/create'
    | '/profile/done'
    | '/profile/select'
    | '/login-bonus/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  ErrorRoute: typeof ErrorRoute
  ProfileCreateRoute: typeof ProfileCreateRoute
  ProfileDoneRoute: typeof ProfileDoneRoute
  ProfileSelectRoute: typeof ProfileSelectRoute
  LoginBonusIndexRoute: typeof LoginBonusIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-bonus/': {
      id: '/login-bonus/'
      path: '/login-bonus'
      fullPath: '/login-bonus'
      preLoaderRoute: typeof LoginBonusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/select': {
      id: '/profile/select'
      path: '/profile/select'
      fullPath: '/profile/select'
      preLoaderRoute: typeof ProfileSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/done': {
      id: '/profile/done'
      path: '/profile/done'
      fullPath: '/profile/done'
      preLoaderRoute: typeof ProfileDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/profile/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  ErrorRoute: ErrorRoute,
  ProfileCreateRoute: ProfileCreateRoute,
  ProfileDoneRoute: ProfileDoneRoute,
  ProfileSelectRoute: ProfileSelectRoute,
  LoginBonusIndexRoute: LoginBonusIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
